In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/anvitkumar/shopping-dataset/lounge-shorts.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/bra.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/ethnic-dresses.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/duffel-bag.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/mangalsutra.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/sunglasses.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/dresses.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/clutches.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/kurta-sets.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/earrings.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/ring.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/clothing-set.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/trunk.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/thermal-bottoms.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/wall-art.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/face-moisturisers.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/belts.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/wallets.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/sweatshirts.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/casual-shoes.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/flip-flops.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/pillow-covers.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/hair-cream-and-mask.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/briefs.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/gloves.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/headphones.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/shirts.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/caps.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/shorts.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/bedsheets.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/co-ords.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/skirts.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/shampoo-and-conditioner.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/runners.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/face-wash-and-cleanser.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/scarves.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/sports-shoes.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/README.md
/kaggle/input/datasets/anvitkumar/shopping-dataset/hair-brush-and-comb.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/sherwani.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/saree-blouse.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/foundation.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/home-fragrance-set.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/innerwear-vests.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/sandals.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/candle-holders.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/yoga-mats.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/dinnerware.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/swim-tops.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/lounge-tshirts.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/jeans.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/hair-accessory.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/towel-set.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/lipstick.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/kurtas.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/tunics.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/nightdress.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/lounge-pants.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/bracelet.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/heels.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/outdoor-masks.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/trousers.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/night-suits.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/dupatta.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/tshirts.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/tops.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/tights.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/camisoles.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/curtains-and-sheers.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/bodysuit.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/showpieces.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/table-covers.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/track-pants.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/boots.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/kurtis.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/hair-masks.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/shaving-essentials.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/jackets.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/cutlery.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/jumpsuit.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/backpacks.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/handbags.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/dungarees.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/bathroom-accessories.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/bath-towels.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/trolley-bag.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/floor-mats--dhurries.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/sweaters.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/Combined_dataset.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/mobile-accessories.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/flats.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/formal-shoes.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/bath-robe.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/chair-cover.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/palazzos.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/sarees.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/watches.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/boxers.csv
/kaggle/input/datasets/anvitkumar/shopping-dataset/perfume-and-body-mist.csv

In [2]:
import os

os.listdir('/kaggle/input')

['datasets']

In [3]:
import pandas as pd

# Load dataset
df = pd.read_csv('/kaggle/input/datasets/anvitkumar/shopping-dataset/Combined_dataset.csv')

# Display first 5 rows
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [4]:
df.shape

(1000, 24)

In [5]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [6]:
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 187.6+ KB

In [8]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [9]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [10]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [13]:
df.fillna("Unknown", inplace=True)

In [14]:
df = df.drop_duplicates()

print("Duplicates removed")

Duplicates removed

In [16]:
print(df.columns)

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [17]:
df[['title', 'seller_name', 'final_price']]

              title     seller_name   final_price
0       Lino Perros         Unknown   "₹3,995.00"
1    Tommy Hilfiger         Unknown   "₹2,899.00"
2             Lavie         Unknown   "₹2,999.00"
3            F Gear         Unknown   "₹1,675.00"
4         MYTRIDENT         Unknown   "₹2,899.00"
..              ...             ...           ...
995           KREDO         Unknown  "₹11,890.00"
996           GUESS         Unknown   "₹8,900.00"
997        GIORDANO         Unknown   "₹7,950.00"
998        Fastrack  Tru███m R███il   "₹2,636.00"
999         BOLDFIT         Unknown     "₹699.00"

[1000 rows x 3 columns]

In [19]:
# Convert final_price to numeric
df['final_price'] = pd.to_numeric(df['final_price'], errors='coerce')

# Convert initial_price also
df['initial_price'] = pd.to_numeric(df['initial_price'], errors='coerce')

In [20]:
filtered_df = df[df['final_price'] > 1000]

filtered_df.head()

Empty DataFrame
Columns: [product_id, title, product_description, rating, ratings_count, initial_price, discount, final_price, currency, images, delivery_options, product_details, breadcrumbs, product_specifications, amount_of_stars, what_customers_said, seller_name, sizes, videos, seller_information, variations, best_offer, more_offers, category]
Index: []

[0 rows x 24 columns]

In [21]:
df['discount_amount'] = df['initial_price'] - df['final_price']

df[['initial_price', 'final_price', 'discount_amount']].head()

   initial_price  final_price  discount_amount
0           3995          NaN              NaN
1           2899          NaN              NaN
2           2999          NaN              NaN
3           1675          NaN              NaN
4           2899          NaN              NaN

In [22]:
df.to_csv('/kaggle/working/cleaned_shopping_data.csv', index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

# Summary

- Loaded the shopping dataset using Pandas.
- Explored dataset structure, columns, and data types.
- Identified and handled missing values.
- Removed duplicate records.
- Performed filtering and column selection.
- Created a derived column named discount_amount.
- Saved the cleaned dataset as a new CSV file.